### ISSUE TITLE
"Visited Pages Count" not working in the profile page 

### ISSUE THREAD

**Issue by Tubaleviao** [Tubaleviao/tuba.work#1]
When we click on our username (rigth top of the page) the pages isn't loaded for some reason.

**Comment by haichuan0424** [comment]
I’d like to give this issue a try.

**Comment by Tubaleviao** [comment]
Man, you are totally welcome! Just reach me out if you have some questions. Have fun!

**Comment by Tubaleviao** [comment]
Tip: The problem happens when retrieving data from the database, inside the mongo.js file.

**Comment by Tubaleviao** [comment]
@haichuan0424 https://mongodb.github.io/node-mongodb-native/2.0/tutorials/aggregation/
