### ISSUE TITLE
Convert to ES6

### ISSUE THREAD

**Issue by Tubaleviao** [Tubaleviao/tuba.work#2]
Convert some scripts to new ES6 good practices in .js files.

**Comment by mugnimaestra** [comment]
Hello, I can take this one, how about the scope? all of .js files included with ejs?

**Comment by mcvladthegoat** [comment]
@Tubaleviao i'm ready to help you :)

**Comment by Tubaleviao** [comment]
@mcvladthegoat just go for it, you're welcome o/

**Comment by Tubaleviao** [comment]
Not much left to change
